site:

url: http://replica-eco.net/
baseurl: ''

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /mis/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 6
paginate_path: "/mission/page:num/"


logo: /images/replica_logo_2.jpeg

social:
  name: Replica Economics
  links:
    - https://facebook.com/ReplicaEconomics

defaults:
  - scope:
      path: ""
    values:
      image: /images/replica_logo_2.jpeg
      author: Replica Economics
      
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234      
